import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import Header from "@/components/Header";
import ViewCanvas from "@/components/ViewCanvas";

const alpino = localFont({
  src: '../public/fonts/Alpino-Variable.woff',
  display: 'swap',
  weight: "100 900",
  variable: "--font-alpino"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`$${alpino.variable} antialiased overflow-x-hidden bg-yellow-300`}
      >
        <Header />
        <main>
          {children}
          <ViewCanvas />
        </main>
      </body>
    </html>
  );
}
